export function AppsPage() {
  return (
    <div className="app-frame-content" style={{ padding: 32, overflow: "auto" }}>
      <p>Adobe creative applications empower millions of professionals worldwide to bring their ideas to life. From photo editing and graphic design to video production and web development, the suite of tools available through Creative Cloud covers every aspect of the creative workflow. Whether you are a seasoned professional or just starting out, these applications provide the foundation for exceptional creative work.</p>
      <p>Photoshop remains the industry standard for image editing and digital art creation. With powerful features like generative fill, neural filters, and advanced compositing tools, it continues to push the boundaries of what is possible in digital imaging. Designers, photographers, and artists rely on Photoshop daily to transform their visions into reality.</p>
      <p>Illustrator provides the ultimate vector graphics experience for designers working on logos, icons, typography, and complex illustrations. Its precision tools and seamless integration with other Creative Cloud applications make it indispensable for brand identity work, print design, and scalable artwork that looks perfect at any size.</p>
      <p>Lightroom streamlines the photo editing workflow with powerful organization and batch processing capabilities. Its non-destructive editing approach means photographers can experiment freely without worrying about losing their original files. Cloud-based syncing ensures your entire library is accessible from any device.</p>
      <p>Premiere Pro delivers professional-grade video editing tools used by filmmakers, content creators, and broadcast professionals around the world. Its timeline-based editing, multi-cam support, and deep integration with After Effects and Audition make it the go-to choice for video production at every scale.</p>
      <p>After Effects brings motion graphics and visual effects to life with an extensive set of compositing and animation tools. From simple title sequences to complex particle simulations, After Effects gives artists the creative freedom to design stunning visual experiences for film, television, and digital media.</p>
      <p>InDesign is the leading layout and publishing application for creating print and digital documents. Magazines, brochures, books, and interactive PDFs all benefit from its sophisticated typography controls, master page system, and seamless integration with Photoshop and Illustrator assets.</p>
      <p>XD and Figma integration within the Adobe ecosystem enables designers to prototype and collaborate on user experiences more efficiently than ever. From wireframes to high-fidelity interactive prototypes, the design-to-development handoff process has been streamlined to reduce friction and improve communication between teams.</p>
      <p>Adobe Express democratizes design by making professional-quality creative tools accessible to everyone. With thousands of templates, a vast library of stock assets, and intuitive editing capabilities, anyone can create social media content, flyers, presentations, and more without specialized design training.</p>
      <p>The Creative Cloud ecosystem continues to evolve with artificial intelligence features powered by Adobe Firefly. Generative AI capabilities are being woven into applications across the suite, enabling creators to work faster, explore more ideas, and push creative boundaries in ways that were previously unimaginable.</p>
    </div>
  );
}
